-- JW Web — seed template
--
-- The real seed file (supabase/seed.sql) holds actual plant financials and is
-- deliberately not committed. This template shows the shape; fill in your own
-- figures, or generate the file from a spreadsheet.
--
-- Run AFTER schema.sql, in the Supabase SQL Editor.
-- Safe to re-run: every row upserts on (plant, month).

do $$
declare
  seed_year int := 2026;
begin

-- One row per (plant, month). Revenue is normally imported from the sales file
-- through the app; seed it here only when backfilling history.
insert into public.revenue (plant, month, revenue)
values
  ('Indore', make_date(seed_year, 1, 1), 0),
  ('Purnia', make_date(seed_year, 1, 1), 0),
  ('Kundli', make_date(seed_year, 1, 1), 0),
  ('UD',     make_date(seed_year, 1, 1), 0),
  ('Rebela', make_date(seed_year, 1, 1), 0)
on conflict (plant, month) do update
  set revenue = excluded.revenue,
      source_file = 'seed';

-- Only the input columns are listed. job_work, fixed_cost, total_cost,
-- actual_jw_per_kg, ppp and jw_pct_of_rev are generated by the database.
insert into public.entries (
  plant, mfg_type, month, working_days, production_kgs, man_days,
  electricity, rent, monthly_expense, reimbursement, revenue
)
values
  ('Indore', 'In House', make_date(seed_year, 1, 1), 26, 0, 0, 0, 0, 0, 0, 0),
  ('Purnia', 'In House', make_date(seed_year, 1, 1), 26, 0, 0, 0, 0, 0, 0, 0),
  ('Kundli', 'In House', make_date(seed_year, 1, 1), 26, 0, 0, 0, 0, 0, 0, 0),
  ('UD',     '3P',       make_date(seed_year, 1, 1), 26, 0, 0, 0, 0, 0, 0, 0),
  ('Rebela', '3P',       make_date(seed_year, 1, 1), 26, 0, 0, 0, 0, 0, 0, 0)
on conflict (plant, month) do update
  set mfg_type        = excluded.mfg_type,
      working_days    = excluded.working_days,
      production_kgs  = excluded.production_kgs,
      man_days        = excluded.man_days,
      electricity     = excluded.electricity,
      rent            = excluded.rent,
      monthly_expense = excluded.monthly_expense,
      reimbursement   = excluded.reimbursement,
      revenue         = excluded.revenue;

end $$;
